# Generated by Django 5.0.1 on 2024-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="added_to_attachment_menu",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_join_groups",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="can_read_all_group_messages",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_premium",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="language_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="supports_inline_queries",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
