# Generated by Django 5.0.1 on 2024-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_projectsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="telegram_webhook_pid",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="telegram_webhook_url",
            field=models.URLField(default=None, null=True),
        ),
    ]
